import 'package:flutter_space_scutum_test/di/injector.config.dart';
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

/// Global instance of GetIt used for dependency injection.
///
/// This instance is shared across the entire application and is responsible
/// for storing and providing configured services, repositories, use cases, etc.
final GetIt getIt = GetIt.instance;

/// Initializes all dependencies generated by Injectable.
///
/// Parameters:
/// - [environment] — specifies which environment configuration to load
///   (e.g., `dev`, `prod`). This determines which annotated classes
///   like `@dev` or `@prod` will be used.
///
/// The `@InjectableInit` annotation tells Injectable to generate
/// the `$initGetIt` initializer inside `injector.config.dart`.
///
/// Usage:
/// ```dart
/// configureDependencies(Environment.dev);
/// ```
@InjectableInit(initializerName: r'$initGetIt', preferRelativeImports: true, asExtension: true)
void configureDependencies(String environment) => getIt.$initGetIt(environment: environment);

/// Retrieves an instance of the specified type [T] from GetIt.
///
/// Optional parameters:
/// - [instanceName] — retrieve a named registration
/// - [param1], [param2] — for factory constructors that require parameters
///
/// Usage:
/// ```dart
/// final repo = inject<TaskRepository>();
/// final client = inject<RestClient>();
/// ```
T inject<T extends Object>({String? instanceName, dynamic param1, dynamic param2}) =>
    GetIt.I.get<T>(instanceName: instanceName, param1: param1, param2: param2);
